### ISSUE TITLE
ProTourPanel Invalid Round

### ISSUE THREAD

**Issue by Acidion** [Perwahl/DGV_Public#7]
The ProTourPanel counts a round with any score above 0 but below 999 as valid. 

Lower bound should likely be if someone aced every hole (I think this would be score.pars.Length and/or score.scores.Length ?).

**Comment by Perwahl** [comment]
Thanks for the feedback! That is just for front end display, actual validation happens server side.

**Comment by Acidion** [comment]
Good to hear! Closing this as its not an actual issue.
